-- svlangserver (IMC Trading, @imc-trading/svlangserver v0.4.1) for NvChad.
-- Generated by offline installer. Edit priorities if needed.
--
-- Priority chain on systemverilog / verilog buffers (matches slang-server.lua):
--   1. svlangserver         ~/.local/usr/bin/svlangserver
--   2. verible-verilog-ls   sibling cross-build (also works on RHEL x86_64)
--   3. slang-server         hudson-trading fallback, requires Slang build
--
-- Override the binary path with $SVLANGSERVER_BIN or vim.g.svlangserver_bin.

local function default_bin()
    return vim.fn.expand("$HOME") .. "/.local/usr/bin/svlangserver"
end

local function resolve_bin()
    local env = vim.env and vim.env.SVLANGSERVER_BIN
    local g = vim.g.svlangserver_bin
    if env and env ~= "" then
        return env
    end
    if g and g ~= "" then
        return g
    end
    return default_bin()
end

local function pick_cmd()
    local bin = resolve_bin()
    if vim.fn.filereadable(bin) == 1 or vim.fn.executable(bin) == 1 then
        return { name = "svlangserver", cmd = { bin, "--stdio" } }
    end
    if vim.fn.executable("verible-verilog-ls") == 1 then
        return { name = "verible-verilog-ls", cmd = { "verible-verilog-ls" } }
    end
    return nil
end

return {
    -- LSP-capable plugin in NvChad is nvim-lspconfig. We piggy-back on its
    -- setup so capabilities match the existing lspconfig setup in
    -- lua/configs/lspconfig.lua.
    {
        "neovim/nvim-lspconfig",
        ft = { "systemverilog", "verilog" },
        config = function()
            local pick = pick_cmd()
            if not pick then
                return
            end

            local cfg = {
                cmd = pick.cmd,
                filetypes = { "systemverilog", "verilog" },
                root_markers = { ".git", "Makefile", "*.f", "*.sv" },
                single_file_support = true,
            }

            -- vim.lsp.config (0.11+) is the modern API; pcall in case a host
            -- is still on the legacy nvim-lspconfig-only setup.
            local ok = pcall(vim.lsp.config, pick.name, cfg)
            if ok then
                vim.lsp.enable(pick.name)
            else
                local lspconfig = require("lspconfig")
                lspconfig[pick.name].setup(cfg)
            end
        end,
    },
}
